syntax = "proto3";

package password;

// Option go_package define a pasta onde os arquivos Go gerados serão criados.
option go_package = "github.com/jvlerner/auth-system/internal/password/proto";

// PasswordService define as RPCs para lidar com hashes Argon2id pesados independentemente da API.
service PasswordService {
  // Hash recebe uma senha em plain text e retorna o hash Argon2id gerado
  rpc Hash (HashRequest) returns (HashResponse);

  // Compare recebe uma senha texto e o hash para validar se conferem
  rpc Compare (CompareRequest) returns (CompareResponse);
}

message HashRequest {
  string plain_text = 1;
}

message HashResponse {
  string hash = 1;
}

message CompareRequest {
  string plain_text = 1;
  string hash = 2;
}

message CompareResponse {
  bool match = 1;
  bool needs_upgrade = 2;
}
