// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: internal/password/proto/password.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HashRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlainText     string                 `protobuf:"bytes,1,opt,name=plain_text,json=plainText,proto3" json:"plain_text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HashRequest) Reset() {
	*x = HashRequest{}
	mi := &file_internal_password_proto_password_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HashRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HashRequest) ProtoMessage() {}

func (x *HashRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_password_proto_password_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HashRequest.ProtoReflect.Descriptor instead.
func (*HashRequest) Descriptor() ([]byte, []int) {
	return file_internal_password_proto_password_proto_rawDescGZIP(), []int{0}
}

func (x *HashRequest) GetPlainText() string {
	if x != nil {
		return x.PlainText
	}
	return ""
}

type HashResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hash          string                 `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HashResponse) Reset() {
	*x = HashResponse{}
	mi := &file_internal_password_proto_password_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HashResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HashResponse) ProtoMessage() {}

func (x *HashResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_password_proto_password_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HashResponse.ProtoReflect.Descriptor instead.
func (*HashResponse) Descriptor() ([]byte, []int) {
	return file_internal_password_proto_password_proto_rawDescGZIP(), []int{1}
}

func (x *HashResponse) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

type CompareRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlainText     string                 `protobuf:"bytes,1,opt,name=plain_text,json=plainText,proto3" json:"plain_text,omitempty"`
	Hash          string                 `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompareRequest) Reset() {
	*x = CompareRequest{}
	mi := &file_internal_password_proto_password_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompareRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompareRequest) ProtoMessage() {}

func (x *CompareRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_password_proto_password_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompareRequest.ProtoReflect.Descriptor instead.
func (*CompareRequest) Descriptor() ([]byte, []int) {
	return file_internal_password_proto_password_proto_rawDescGZIP(), []int{2}
}

func (x *CompareRequest) GetPlainText() string {
	if x != nil {
		return x.PlainText
	}
	return ""
}

func (x *CompareRequest) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

type CompareResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Match         bool                   `protobuf:"varint,1,opt,name=match,proto3" json:"match,omitempty"`
	NeedsUpgrade  bool                   `protobuf:"varint,2,opt,name=needs_upgrade,json=needsUpgrade,proto3" json:"needs_upgrade,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompareResponse) Reset() {
	*x = CompareResponse{}
	mi := &file_internal_password_proto_password_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompareResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompareResponse) ProtoMessage() {}

func (x *CompareResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_password_proto_password_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompareResponse.ProtoReflect.Descriptor instead.
func (*CompareResponse) Descriptor() ([]byte, []int) {
	return file_internal_password_proto_password_proto_rawDescGZIP(), []int{3}
}

func (x *CompareResponse) GetMatch() bool {
	if x != nil {
		return x.Match
	}
	return false
}

func (x *CompareResponse) GetNeedsUpgrade() bool {
	if x != nil {
		return x.NeedsUpgrade
	}
	return false
}

var File_internal_password_proto_password_proto protoreflect.FileDescriptor

const file_internal_password_proto_password_proto_rawDesc = "" +
	"\n" +
	"&internal/password/proto/password.proto\x12\bpassword\",\n" +
	"\vHashRequest\x12\x1d\n" +
	"\n" +
	"plain_text\x18\x01 \x01(\tR\tplainText\"\"\n" +
	"\fHashResponse\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\tR\x04hash\"C\n" +
	"\x0eCompareRequest\x12\x1d\n" +
	"\n" +
	"plain_text\x18\x01 \x01(\tR\tplainText\x12\x12\n" +
	"\x04hash\x18\x02 \x01(\tR\x04hash\"L\n" +
	"\x0fCompareResponse\x12\x14\n" +
	"\x05match\x18\x01 \x01(\bR\x05match\x12#\n" +
	"\rneeds_upgrade\x18\x02 \x01(\bR\fneedsUpgrade2\x88\x01\n" +
	"\x0fPasswordService\x125\n" +
	"\x04Hash\x12\x15.password.HashRequest\x1a\x16.password.HashResponse\x12>\n" +
	"\aCompare\x12\x18.password.CompareRequest\x1a\x19.password.CompareResponseB9Z7github.com/jvlerner/auth-system/internal/password/protob\x06proto3"

var (
	file_internal_password_proto_password_proto_rawDescOnce sync.Once
	file_internal_password_proto_password_proto_rawDescData []byte
)

func file_internal_password_proto_password_proto_rawDescGZIP() []byte {
	file_internal_password_proto_password_proto_rawDescOnce.Do(func() {
		file_internal_password_proto_password_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_password_proto_password_proto_rawDesc), len(file_internal_password_proto_password_proto_rawDesc)))
	})
	return file_internal_password_proto_password_proto_rawDescData
}

var file_internal_password_proto_password_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_internal_password_proto_password_proto_goTypes = []any{
	(*HashRequest)(nil),     // 0: password.HashRequest
	(*HashResponse)(nil),    // 1: password.HashResponse
	(*CompareRequest)(nil),  // 2: password.CompareRequest
	(*CompareResponse)(nil), // 3: password.CompareResponse
}
var file_internal_password_proto_password_proto_depIdxs = []int32{
	0, // 0: password.PasswordService.Hash:input_type -> password.HashRequest
	2, // 1: password.PasswordService.Compare:input_type -> password.CompareRequest
	1, // 2: password.PasswordService.Hash:output_type -> password.HashResponse
	3, // 3: password.PasswordService.Compare:output_type -> password.CompareResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_password_proto_password_proto_init() }
func file_internal_password_proto_password_proto_init() {
	if File_internal_password_proto_password_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_password_proto_password_proto_rawDesc), len(file_internal_password_proto_password_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_password_proto_password_proto_goTypes,
		DependencyIndexes: file_internal_password_proto_password_proto_depIdxs,
		MessageInfos:      file_internal_password_proto_password_proto_msgTypes,
	}.Build()
	File_internal_password_proto_password_proto = out.File
	file_internal_password_proto_password_proto_goTypes = nil
	file_internal_password_proto_password_proto_depIdxs = nil
}
